name: Build and Push Docker Image with Dynamic Versioning

on:
  push:
    tags:
      - 'v*.*.*' # Trigger Tags Version
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    # Step 1: Checkout source code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (optional but recommended for building multi-platform images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from Git tag
      id: extract_version
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
        else
          echo "VERSION=latest" >> $GITHUB_ENV
        fi
        echo "Version is set to ${{ env.VERSION }}"

    # Step 5: Build and push Docker image
    # Tag with the new version
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/apps:${{ env.NEXT_VERSION }}
