name: CI/CD Pipeline to Docker Registry

on:
  push:
    branches:
      - main  # Jalankan pipeline setiap ada push ke branch "main"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub (atau registry lain)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Get the latest version from tags
      - name: Get Next Version
        id: version
        run: |
          # Fetch all tags
          git fetch --tags
          # Get the latest tag
          LAST_TAG=$(git tag --sort=-creatordate | head -n 1)
          # Determine the next version
          if [ -z "$LAST_TAG" ]; then
            NEXT_VERSION="v1"  # If no tags exist, start with v1
          else
            # Increment version
            NEXT_VERSION=$(echo $LAST_TAG | awk -F. -v OFS=. '{$NF++; print}')
          fi
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      # Build the Docker image
      - name: Build Docker image
        run: |
          echo "Building Docker image with version: $NEXT_VERSION"
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/apps:$NEXT_VERSION
          docker tag ${{ secrets.DOCKER_USERNAME }}/apps:$NEXT_VERSION

      # Push the Docker image to the registry
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/apps:$NEXT_VERSION
