name: Build and Push Docker Image with Dynamic Versioning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    # Step 1: Checkout source code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (optional but recommended for building multi-platform images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Get the next version
    - name: Get Next Version
      id: version
      run: |
        # Fetch all tags
        git fetch --tags
        # Get the latest tag
        LAST_TAG=$(git tag --sort=-creatordate | head -n 1)
        # Determine the next version
        if [ -z "$LAST_TAG" ]; then
          NEXT_VERSION="v1"  # If no tags exist, start with v1
        else
          # Increment version by 1
          VERSION_NUMBER=$(echo $LAST_TAG | sed 's/v//')  # Remove 'v' prefix
          NEXT_VERSION="v$((VERSION_NUMBER + 1))"
        fi
        echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

    # Step 5: Build and push Docker image
    # Tag with the new version
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/apps:${{ env.NEXT_VERSION }}
